### ISSUE TITLE
'Always on visible workspace'

### ISSUE THREAD

**Issue by pszafer** [spin83/multi-monitors-add-on#10]
Hello,
First - great extensions, thanks for that! :+1: 
Now, issue.

When I choose 'Always on visible workspace' option, if changing workspaces by keyboard shortcut (CTRL+Alt+Arrow Up/Down) everything is fine, but when I'm changing workspace by mouse window app is not visible on all workspaces.

**Comment by spin83** [comment]
I can't reproduce this bug. What is your version of gnome-shell and what extensions do you use.

**Comment by pszafer** [comment]
It wasn't working in GNOME Shell 3.16, but it's working right now... in GNOME Shell 3.16.1.
So issue closed, thanks for support!
