### ISSUE TITLE
Workspace not showing on secondary screen

### ISSUE THREAD

**Issue by blouargant** [spin83/multi-monitors-add-on#103]
Workspaces are not displayed on secondary screen.
The error is the following:
JS ERROR: Extension multi-monitors-add-on@spin83: Error: GSettings key enable-hot-corners not found in schema org.gnome.shell
   _checkKey@resource:///org/gnome/gjs/modules/overrides/Gio.js:563:23
   _init/createCheckedMethod/<@resource:///org/gnome/gjs/modules/overrides/Gio.js:528:13
   showPanel/Main.layoutManager._updateHotCorners@/home/bertrand/.local/share/gnome-shell/extensions/multi-monitors-add-on@spin83/mmlayout.js:109:18
   showPanel@/home/bertrand/.local/share/gnome-shell/extensions/multi-monitors-add-on@spin83/mmlayout.js:137:5
...

The key is actually in org.gnome.desktop.interface not in org.gnome.shell.
If I disable the code line 109 in mmlayout.js then workspaces are showing up again.

**Comment by ruedigerkupper** [comment]
Confirming the problem and the workaround.
Possibly related: #34

**Comment by borismu** [comment]
Just upgraded from Ubuntu 19.04 to 19.10. In 19.04 extension was working perfectly. 
In 19.10 had the same error as @blouargant and workaroound worked for me. Thank you
