### ISSUE TITLE
Fails to install when No Hot Corner extension is installed

### ISSUE THREAD

**Issue by rick-pri** [spin83/multi-monitors-add-on#105]
If you have **[this](https://extensions.gnome.org/extension/118/no-topleft-hot-corner/
)** extension installed it causes an error when installing this plugin.

JS error:
```
JS ERROR: Extension multi-monitors-add-on@spin83: Error: GSettings key enable-hot-corners not found in schema org.gnome.shell#012_checkKey@resource:///org/gnome/gjs/modules/overrides/Gio.js:563:23#012_init/createCheckedMethod/<@resource:///org/gnome/gjs/modules/overrides/Gio.js:528:13#012showPanel/Main.layoutManager._updateHotCorners@/home/richard/.local/share/gnome-shell/extensions/multi-monitors-add-on@spin83/mmlayout.js:109:18#012showPanel@/home/richard/.local/share/gnome-shell/extensions/multi-monitors-add-on@spin83/mmlayout.js:137:5#012enable@/home/richard/.local/share/gnome-shell/extensions/multi-monitors-add-on@spin83/extension.js:209:3#012wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22#012enable@/home/richard/.local/share/gnome-shell/extensions/multi-monitors-add-on@spin83/extension.js:331:2#012_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:132:13#012loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:264:21#012callback@resource:///org/gnome/shell/ui/extensionDownloader.js:244:17#012gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:108:13
```

**Comment by rick-pri** [comment]
I've found that if you uninstall the No hot corner extension, install this extension and then reinstall the no hot corner extension then both will work together it seems.

**Comment by LuLeRoemer** [comment]
I experience the same issue without having "No Hot Corner extension" installed. I'm using Ubuntu 19.10 (GNOME 3.34.1) where hot corners no longer exist, I guess.

**Comment by fjssilva** [comment]
I too don't have the "No Topleft Hot Corner" extension. But the error message points to the setting  not `org.gnome.shell#enable-hot-corners` which I don't find in dconf, `org.gnome.desktop.interface#enable-hot-corners` exists though.

**Comment by furai** [comment]
I'm having same issue. Fresh upgrade to Ubuntu 19.10.

**Comment by rick-pri** [comment]
Okay, so as I understand it the Gnome developers removed, or at least disabled by default, the hot corners support.  As such, if this extension is expecting this functionality this may explain why it has issues now that the feature has gone.
