### ISSUE TITLE
Error loading extension, yet still works, throwing errors constantly

### ISSUE THREAD

**Issue by BloodyIron** [spin83/multi-monitors-add-on#107]
I think this is related to #105, except that I have slightly different results.

It is installed, and works, mostly. However on all the systems I use it on, it is constantly complaining about an error, and it looks to be related to the hot corner aspect:

> Dec 10 21:14:20 BloodyIron net.lutris.Lutris.desktop[1964]: [27430:27430:1210/211420.547598:ERROR:sandbox_linux.cc(369)] InitializeSandbox() called with multiple threads in process gpu-process.
                                              showPanel/Main.layoutManager._updateHotCorners@/home/bloodyiron/.local/share/gnome-shell/extensions/multi-monitors-add-on@spin83/mmlayout.js:109:18

I'm on Ubuntu 19.10, and this has never stopped complaining about throwing errors.

Can we PLEASE get an update to this lovely extension? It's seriously helpful.

**Comment by universam1** [comment]
same here on Ubuntu 19.10

**Comment by BloodyIron** [comment]
Still getting errors, can we PLEASE have this fixed? 19.10 has been out for many months now.

**Comment by ser** [comment]
On gnome 3.36 it stopped working at all.

**Comment by BloodyIron** [comment]
YIKES!

**Comment by andrecastillo** [comment]
Gnome 3.34.2 on ubuntu 19.10, extension doesn't work. I see the extension in my notifications bar up top, but none of the features work. I'd like to help fix if I can. I've never worked on a project like this, anyone can point me to some info that can get me started?

**Comment by yuriw** [comment]
I see the same on 20.04
Not sure if it works.  In my case I want to see Date Time button, but can't find it.
How does it look like or where to find it  ?

**Comment by BloodyIron** [comment]
Is this _EVER_ going to get fixed? I haven't seen a single developer chime in or anything done related to this :/

Originally reported this over a year ago. I bet this would be a quick fix too, like cmon...

**Comment by yuriw** [comment]
@BloodyIron do you know any work around or similar tool?  All I need to show top title with clock on all monitors.  Lost my old laptop :(

**Comment by BloodyIron** [comment]
I don't know of an alternative tool. The "work-around" (which is limited in reliability) is, in Gnome Tweaks, toggle the addon of, reboot, after login toggle it back on, configure it how you want. It should generally work, but still throw errors. Sometimes I need to toggle it off, reboot, then back on, for one of my systems, but not all.

Unsure if that'll work for you, it might, best I have I'm afraid.

**Comment by yuriw** [comment]
I can't even toggle the add on button, see attached 

![image](https://user-images.githubusercontent.com/387
6474/79609536-c587dd80-80ab-11ea-8761-1b7c68763617.png)

**Comment by BloodyIron** [comment]
> I can't even toggle the add on button, see attached
> 
> ![image](https://user-images.githubusercontent.com/3876474/79609562-d33d6300-80ab-11ea-83ba-de3c04f58410.png)

It would not let me toggle the extension on/off until it was after a fresh reboot. Try that.

**Comment by yuriw** [comment]
oh have done it may times :(

**Comment by yuriw** [comment]
@BloodyIron this is not directly related to this issue, although I am trying to workaround.  Do you know where to toggle 'always on visible workspace' option?  I currently have it only on primary screen, but want to have on all.

![image](https://user-images.githubusercontent.com/3876474/79670066-1adbf180-8175-11ea-9638-6a349d23fa80.png)

**Comment by BloodyIron** [comment]
Just updated, and not seeing errors so far. If I have issues, I'll report back. Thanks @spin83 ! :DDD

Been waiting for this one for a loooong while :P
