### ISSUE TITLE
Disbale hot corner on second monitor

### ISSUE THREAD

**Issue by WuerfelDev** [spin83/multi-monitors-add-on#115]
As other people already pointed out, its easy to accidentally activate the hot corner on the second screen.
Can we get a toggle to disable the hot corner there? Disabling "Activities" doesn't affect the hot corner

**Comment by WuerfelDev** [comment]
This can be worked around by using https://github.com/janxyz/custom-hot-corners

**Comment by mrLob** [comment]
> This can be worked around by using https://github.com/janxyz/custom-hot-corners

++ 
some fix it
but by default in extention for multimonitor it not best feature(hot corner)

**Comment by spin83** [comment]
Fixed in recent version (v22).
