### ISSUE TITLE
3.36.4 Broke the Extension

### ISSUE THREAD

**Issue by jdaeira** [spin83/multi-monitors-add-on#125]
The newest update to 3.36.4 broke this extension. When in overview mode some windows open from other workspaces show up in current workspace. Also the thumbnail slider does not show pop out.

**Comment by xhess** [comment]
I can confirm this. The extension does not crash, but in overview mode all the windows from all workspaces show up and the windows don't get scaled down in the overview, they rather get trimmed down.
![screenshot-trimmed-window-in-overview-gnome-3-36-4](https://user-images.githubusercontent.com/8003646/87007654-e2bbdc00-c1c2-11ea-83eb-e0792509f5e4.png)

**Comment by jdaeira** [comment]
Yes. You're description of the issue is spot on.

**Comment by DazeEnd** [comment]
Same problem here.

**Comment by phaleintx** [comment]
Verified the issue on the latest version of Fedora 32 Workstation. gnome-shell-3.36.4-1.fc32.x86_64

**Comment by janvonde** [comment]
for me, too.

**Comment by mumoao** [comment]
Hi all, 
Same problem here on Fedora 32 Workstation edition with gnome-shell-3.36.4-1.fc32.x86_64.
`journalctl -f` gives the following each time Super (Windows) Key is used:

```
Jul 13 17:56:34 localhost.localdomain gnome-shell[2214]: 
JS ERROR: TypeError: area is null
padArea@resource:///org/gnome/shell/ui/workspace.js:1101:9
_updateWindowPositions@resource:///org/gnome/shell/ui/workspace.js:1334:20
_realRecalculateWindowPositions@resource:///org/gnome/shell/ui/workspace.js:1311:14
_recalculateWindowPositions/this._positionWindowsId<@resource:///org/gnome/shell/ui/workspace.js:1286:18
```
I enjoy your GSE. Thank you for solving this.

**Comment by Extraltodeus** [comment]
> Hi all,
> Same problem here on Fedora 32 Workstation edition with gnome-shell-3.36.4-1.fc32.x86_64.
> `journalctl -f` gives the following each time Super (Windows) Key is used:
> 
> ```
> Jul 13 17:56:34 localhost.localdomain gnome-shell[2214]: 
> JS ERROR: TypeError: area is null
> padArea@resource:///org/gnome/shell/ui/workspace.js:1101:9
> _updateWindowPositions@resource:///org/gnome/shell/ui/workspace.js:1334:20
> _realRecalculateWindowPositions@resource:///org/gnome/shell/ui/workspace.js:1311:14
> _recalculateWindowPositions/this._positionWindowsId<@resource:///org/gnome/shell/ui/workspace.js:1286:18
> ```
I confirm having the same error message when using the super key

**Comment by RDurrani** [comment]
Love your extension, but can verify the same issue after updating to gnome 3.36.3 on fedora 32.

**Comment by Extraltodeus** [comment]
Downloaded from the repo. Now it works. Thanks!

**Comment by DazeEnd** [comment]
The new commit (302c28b) fixed it for me as well. Thanks!

**Comment by zeparu** [comment]
can confirm that 3.36.4 broke it, and current master branch fixes it

**Comment by RDurrani** [comment]
Can confirmed. Fix works. Thanks!

**Comment by phaleintx** [comment]
Confirmed new master branch fixes the issue.

**Comment by arakan94** [comment]
When will it be posted on extensions.gnome.org?

**Comment by cj81499** [comment]
@spin83 Any updates? It would be really nice to have this on https://extensions.gnome.org/
