### ISSUE TITLE
Error loading extension

### ISSUE THREAD

**Issue by davidbouche** [spin83/multi-monitors-add-on#126]
Hi,

I'm having an issue to using this -usefull !- extension : 

### The problem

![image](https://user-images.githubusercontent.com/19934334/88544725-1ea3cd80-d01a-11ea-83fe-a6215c5f4725.png)

![image](https://user-images.githubusercontent.com/19934334/88544744-25324500-d01a-11ea-80a9-d4f30e91a1e9.png)

When I'm looking in the logs : 

```
$ sudo journalctl /usr/bin/gnome-shell -f
juil. 27 14:59:38 pcdavid gnome-shell[1952]: Extension "multi-monitors-add-on@spin83" had error: TypeError: GObject.registerClass() used with invalid base class (is PanelMenuButton)
```

### Context : 

```
$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 29 (Twenty Nine)
Release:	29
Codename:	TwentyNine

$ rpm -qa |grep ^gnome-desktop
gnome-desktop3-3.30.2.3-1.fc29.x86_64
```
I had this issue from gnome.org : #125 
I downloaded the last commit (as suggested from here https://github.com/spin83/multi-monitors-add-on/issues/125#issuecomment-660542446)

Thanks for your work, it's really helpfull each days.
David

**Comment by austinkeller** [comment]
I'm not seeing the same issue on my system when I search `journalctl`

```bash
$ lsb_release -a
LSB Version:    n/a
Distributor ID: ManjaroLinux
Description:    Manjaro Linux
Release:        20.0.3
Codename:       Lysia
```

```bash
$ sudo pacman -Qs gnome-desktop
local/gnome-desktop 1:3.36.4-1
    Library with common API for various GNOME modules
```

```bash
$ gnome-shell --version
GNOME Shell 3.36.4
```

Might be because you're using an older release of gnome-shell? I wonder if the original issue in #125 wasn't from gnome-shell 3.36.4 but a dependency?
