### ISSUE TITLE
Multi Monitors Add-On should respect "Activities Overview Hot Corner" setting

### ISSUE THREAD

**Issue by franzs** [spin83/multi-monitors-add-on#129]
Using gnome 3.36.4 disabling the "Activities Overview Hot Corner" setting doesn't have any effect if multi monitors add-on is enabled. It doesn't matter how "Show Activities-Button on additional monitors" is set, btw.

I prefer to disable the activites hor corner and would appreciate if multi monitors add-on could be used without it.

**Comment by Electw** [comment]
I have the same issue, it became quite annoying when overview is accidentally accessed

**Comment by elafaros** [comment]
same issue with me, rather annoying

**Comment by Random-Chain** [comment]
+1 on that. Is there any workaround to disable hot corner?
