### ISSUE TITLE
Allow set the workspace overview per monitor

### ISSUE THREAD

**Issue by BuZZ-dEE** [spin83/multi-monitors-add-on#130]
As far as I can see, it is only possible to set the workspace overview to the right or to the left side. But, I want to set it to the right side for my left monitor and to the left side for my right monitor.

**Comment by axxapy** [comment]
+1. It is needed for 3-monitor setup.
Currently we have only 2 options:

"Default":
![Screenshot from 2020-10-16 21-50-32](https://user-images.githubusercontent.com/3088476/96328612-e8af2d80-0ff9-11eb-9fb1-47880772473d.png)

"Show thumbnails-slider on left side of additional monitors":
![Screenshot from 2020-10-16 21-50-37](https://user-images.githubusercontent.com/3088476/96328615-eea50e80-0ff9-11eb-8de3-9d48b4391223.png)

Both are not 100% usable.

It would amazing if we could configure slider position per-monitor.
