### ISSUE TITLE
Overview is cluttered with Multi monitors add-on

### ISSUE THREAD

**Issue by BuZZ-dEE** [spin83/multi-monitors-add-on#131]
Please see [gnome-shell/-/issues/3036](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/3036). Especially that [comment](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/3036#note_881764).

**Comment by fcastilloec** [comment]
This is a duplicate of #125 and there's a fix 302c28b
