### ISSUE TITLE
3.36.5 causes some slight visual issues

### ISSUE THREAD

**Issue by jacobmischka** [spin83/multi-monitors-add-on#134]
The extension doesn't crash and mostly works, but window rendering is a bit wonky. Title bars are cut off when they are above the top of the slider, and windows clip behind the slider on non-primary monitors.

![image](https://user-images.githubusercontent.com/3939997/91624550-a4db6880-e966-11ea-970f-5f8b7c44cde0.png)

**Comment by jacobmischka** [comment]
Ah, it's because of this commit: 2bf544e2726f238603bb83d6df2f619097028d13

They reverted the changes necessary for 3.36.4. So all that needs to be done is to revert this commit of yours: 302c28b25bb80c11c943a3ea50fcf6bc030b2084

**Comment by Talv** [comment]
Confirming. Reverting patch fixes this for me.
Thanks for looking into this.
```
$ gnome-shell --version
GNOME Shell 3.36.6
```

**Comment by spin83** [comment]
For gnome-shell 3.36.5 and above (3.36.x) please use version 20 of this extension.
