### ISSUE TITLE
Stop mouse on begin/end of panel

### ISSUE THREAD

**Issue by Atema** [spin83/multi-monitors-add-on#14]
On the primary panel, you can't move the mouse further to the right when you're at the end and not moving your cursor extremely fast. I'd love to see this feature on other monitors too, both for the left and the right side of the panel.

**Comment by lcavalli** [comment]
My primary monitor is on the left, secondary on the right, so it is understandable that mouse cursor stops on the left side of the primary monitor. But stopping the mouse cursor on the left side of the secondary monitor with plenty of space on the left is a bit unnatural. I have to move down a few pixels, exit the top panel and then move the mouse to enter the other monitor.
