### ISSUE TITLE
Fedora 33: extension crashing after installation.

### ISSUE THREAD

**Issue by maxwax** [spin83/multi-monitors-add-on#140]
Newly installed Fedora 33 system.
Via the Gnome Shell Extensions website I can install this extension (which I've happily used for many years THANK YOU!)

Upon an attempt to log back in, the system runs into problems with this extension.
This causes the GUI boot up to crash and repeat endlessly. Users are locked out.

Switching to a virtual console and removing this exension from $HOME/.local/share/gnome-extensions stops the repeated failures and returns to a login prompt. A login, without this extension, allows proper operation and other extensions run OK.

Via journalctl I found this:
```Dec 01 00:09:35 sarko.maxlab gnome-shell[25670]: st_widget_get_theme_node called on the widget [0x55a7077f2b00 Gjs_multi-monitors-add-on_spin83_mmoverview_MultiMonitorsControlsManager] which is not in the stage.
Dec 01 00:09:35 sarko.maxlab gnome-shell[25670]: st_widget_get_theme_node called on the widget [0x55a707856990 StBoxLayout "mm-overview-group-1"] which is not in the stage.
Dec 01 00:09:35 sarko.maxlab gnome-shell[25670]: st_widget_get_theme_node called on the widget [0x55a7078646b0 Gjs_multi-monitors-add-on_spin83_mmoverview_MultiMonitorsThumbnailsSlider.overview-controls] which is not in the stage.
Dec 01 00:09:35 sarko.maxlab gnome-shell[25670]: st_widget_get_theme_node called on the widget [0x55a70647cb90 Gjs_multi-monitors-add-on_spin83_mmoverview_MultiMonitorsThumbnailsBox.workspace-thumbnails] which is not in the stage.
Dec 01 00:09:35 sarko.maxlab gnome-shell[25670]: st_widget_get_theme_node called on the widget [0x55a7077f2b00 Gjs_multi-monitors-add-on_spin83_mmoverview_MultiMonitorsControlsManager] which is not in the stage.
Dec 01 00:09:35 sarko.maxlab gnome-shell[25670]: st_widget_get_theme_node called on the widget [0x55a707856990 StBoxLayout "mm-overview-group-1"] which is not in the stage.
Dec 01 00:09:35 sarko.maxlab gnome-shell[25670]: st_widget_get_theme_node called on the widget [0x55a7078646b0 Gjs_multi-monitors-add-on_spin83_mmoverview_MultiMonitorsThumbnailsSlider.overview-controls] which is not in the stage.
Dec 01 00:09:35 sarko.maxlab gnome-shell[25670]: st_widget_get_theme_node called on the widget [0x55a70647cb90 Gjs_multi-monitors-add-on_spin83_mmoverview_MultiMonitorsThumbnailsBox.workspace-thumbnails] which is not in the stage.
```
My system is Fedora 33, fresh install, but with many things being brought back into it such as this GS extension.
Note I'm running X.org instead of Wayland.
I think this issue is likely the same trouble a 'stephenadler' is reporting on the Gnome Shell Extension web page for this extension.
I hope this helps. If I can provide further info, I'm happy to do so. Thanks again,

**Comment by christian-nils** [comment]
I do have the same issue. Fedora 33, gnome 3.38.2.

**Comment by mcardillo55** [comment]
Same on Arch Linux.
gnome-shell 3.38.2-1
linux kernel 5.9.11.arch2-1

**Comment by gherney** [comment]
Same issue after upgrading from Fedora 32 to 33, gnome 3.38.2.  Disabling extension for now.

**Comment by maxwax** [comment]
Installed this version via git on the same system as the original report
1) No problem with install, functionality seems fine
2) No problem with control-R Gnome restart
3) No problem with reboot of system for clean boot into Gnome 3 UI

I'm feeling good that this has fixed the issue.

Thanks very much for creating this in the first place -- been happily using it for years -- and the update to fix this issue. Really appreciated!

**Comment by mcardillo55** [comment]
@spin83 Thanks for the fix! Any way you can push the update to extensions.gnome.org when you get a chance?

**Comment by netronicus** [comment]
is this fixed? I want to install again this extension, I tested the extension on extensions.gnome.org, but I don't know if that is the same version that in here O:

**Comment by netronicus** [comment]
My testing was on Manjaro 20.2.1, Gnome 3.38.3

**Comment by Zappo-II** [comment]
This git version is newer than gnome.org and works for me on manjaro
```
~/.../other-workspace/multi-monitors-add-on >>> cat /etc/lsb-release                                                                                                                          ±[master]
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=20.2.1
DISTRIB_CODENAME=Nibia
DISTRIB_DESCRIPTION="Manjaro Linux"
~/.../other-workspace/multi-monitors-add-on >>>
```

**Comment by maxwax** [comment]
This hasn't been updated in gnome-shell extensions yet, so my solution is to download the source here.

On Fedora, I untar/unzip it and place the 'mult-monitors-add-on@spin83' directory extracted from that archive into $HOME/.local/share/gnome-shell/extensions/multi-monitors-add-on@spin83  .  Don't just unpack the download into that directory, you need the directory from within the archive.

I can check my version by changing to that directory and looking for version within metadata.json

$ grep -ri version metadata.json 
    "shell-version": ["3.38"],
    "version": 22.1

If you're at **extension** version 22.1 or above you should be good.

**Comment by cmcinroy** [comment]
Just wanted to say thanks for this fix. I've been using tolerable workarounds for months, but this fixes both the crash on login and desktop reset issues. :tada: 
(Fedora 33, GNOME 3.38.3)
