### ISSUE TITLE
corrupt AppMenu when Desktop is selected ubuntu 21.04

### ISSUE THREAD

**Issue by GideonUng** [spin83/multi-monitors-add-on#155]
corrupt AppMenu when Desktop is selected
version from extensions.gnome.org/
ubuntu 21.04

![Screenshot from 2021-05-01 02-01-23](https://user-images.githubusercontent.com/5054701/116764456-6e884880-aa21-11eb-8f02-687f6d2c4a06.png)

**Comment by ruedigerkupper** [comment]
Confirming.
Version from Ubuntu repository (23-1).
