### ISSUE TITLE
shell theme

### ISSUE THREAD

**Issue by GLTR87** [spin83/multi-monitors-add-on#21]
First: wonderful extension!
I was wondering if it would be possible to have the additional thumbnail slider match the shell theme?
I use the extension User Themes https://extensions.gnome.org/extension/19/user-themes/
Not a big deal, but it would be nice.
Thanks.

**Comment by spin83** [comment]
Gnome Shell to display default thumbnails slider on right site of the screen use css class “workspace-thumbnails” and this extension to display left site slider use its own css class “workspace-thumbnails-left”. In general, theme overwrite default “workspace-thumbnails” class and it should in the same way overwrite “workspace-thumbnails-left” class.

**Comment by GLTR87** [comment]
Thanks, in my theme's (Arc in my case) gnome-shell.css file, I have duplicated the ".workspace-thumbnails" section and renamed it to ".workspace-thumbnails-left".
Problem solved!

**Comment by smcdougall** [comment]
@spin83

If you wanted to add support for this in the extension, couldn't you change the class to something like `workspace-thumbnails workspace-thumbnails-left` that way it would both inherit the shell theme's styles *and* have your own mirrored styles.  I've never done any Gnome theming, but I assume the concept works the same as writing CSS for the web.

This idea wouldn't be perfect, as anything that had to be flipped would still match the hard-coded styles, but It would at least inherit things like background-color.

Just an idea.  I don't think many theme developers would write styles specifically for your extension though.  This idea could maybe provide a little middle ground.
