### ISSUE TITLE
Not working properly with some 3rd party themes

### ISSUE THREAD

**Issue by brittyazel** [spin83/multi-monitors-add-on#26]
I'm not sure if the issue here is with the themes, or this extension, but some themes (notably adapta) don't look correct on the workspace view on the second monitor.

**Comment by smcdougall** [comment]
As far as I know, this has to do with how the extension styles the second workspace view.  It uses a separate class for this panel and doesn't seem to inherit styles from the theme.

There was a brief discussion of a workaround here: #21

It would be great if there were a proper fix though.  Hopefully that will help a little in the meantime.
