### ISSUE TITLE
Add support fro Fedora 24

### ISSUE THREAD

**Issue by liquidat** [spin83/multi-monitors-add-on#28]
This extension is currently not supported by Fedora 24, since it comes with a newer Gnome version. Can you please provide an upgraded version and submit it to extensions.gnome.org?

**Comment by smcdougall** [comment]
Fedora 24 uses Gnome 3.20, which is the latest release.  This extension *does* support Gnome 3.20, and there are quite a few of us (#24) that have it working under Arch.

I can't verify that the copy on extensions.gnome.org is up-to-date (I'm not on my Gnome machine at the moment), but I don't see why it wouldn't have been updated.

If that version *is* out of date, you could try downloading the version here on GitHub and extracting the `multi-monitors-add-on@spin83` folder into `~/.local/share/gnome-shell/extentions`.  Or you can edit the following line of `metadata.json`, as it's the only thing that has changed:

Change:
```json
"shell-version": ["3.14", "3.16", "3.18"],
```
To:
```json
"shell-version": ["3.14", "3.16", "3.18", "3.20"],
```

If I think of it later, I'll check what version is on extensions.gnome.org.  I can't fix it if it's out-of-date, but I can at least confirm that it needs updating.

Unfortunately, @spin83 isn't on GitHub much.  Hope this helps you out in the meantime. :smiley:

**Comment by liquidat** [comment]
@smcdougall Thanks for the answer, adding the version string helped! I am thus pretty sure the version on extensions.gnome.org is outdated and @spin83 updates it rather quickly.

**Comment by smcdougall** [comment]
Glad it helped.  As far as I know, he's a Fedora user too, so if it is out of date on there, I'm sure he'll be updating it soon.

**Comment by spin83** [comment]
Present version of this extension is on extensions.gnome.org since April 28
and it works properly on fedora24. 
Could you read "version" property from file "metadata.json" ?

**Comment by liquidat** [comment]
There was no upgrade shown so far - but today it is shown. Strange. Sorry for the noise, I'll close the issue.
