### ISSUE TITLE
Weird area at the top of the screen

### ISSUE THREAD

**Issue by hitex** [spin83/multi-monitors-add-on#30]
With this extension enabled the weird area at the top of the screen appears and some gui elements like context menu or desktop files appear lower than that.
Here is the video of the problem: https://vid.me/6z1T

Any ideas why it is happening?

**Comment by AshleighAdams** [comment]
I don't think this is a bug with this addon, I noticed it a lot where other UI toolkits won't make a context menu outside of the bounds of all monitors.  I've also noticed it be fixed and regress in both GTK and Qt multiple times.

For example, the green areas are where context menu items show up with a monitor set lower down: 
![image](https://cloud.githubusercontent.com/assets/182589/16878313/ffb7f1d0-4aa3-11e6-8eb1-159c0738b92d.png)

**Comment by hitex** [comment]
I tested a bit with different monitor arrangements and it behaves really weird.

I have 3 monitor setup and in this arrangement it does not work correctly like in previous video.
![Not working correctly](https://cloud.githubusercontent.com/assets/1055370/16879825/056fba2e-4abb-11e6-8cd2-5204f1d8d133.png)

But if I drag that third monitor a little bit lower - everything seems to work again.
![Working](https://cloud.githubusercontent.com/assets/1055370/16879881/3ff2d398-4abb-11e6-9e1a-deff4ec5de42.png)

When the addon is disabled - then everything works with any arrangement.

**Comment by spin83** [comment]
It look like bug in Gnome (Mutter) or GTK.
To work around that problem all displays must be aligned to top line.

**Comment by hitex** [comment]
This problem has disappeared when I re-positioned my displays a couple of times.
