### ISSUE TITLE
Windows on secondary screen change size and don't animate in overview

### ISSUE THREAD

**Issue by nkovacs** [spin83/multi-monitors-add-on#31]
I have two 1080p monitors and I have enabled the thumbnail slider on the secondary display. Both thumbnail sliders are partially hidden by default. If I hover over the one on the primary display, the windows on the secondary display become bigger (the same size they are when the thumbnail slider on the secondary display is disabled). Hovering the thumbnail slider on the secondary display causes them to jump back to their smaller size.
There's also no animation when the windows on the secondary display move out of the way (when the thumbnail slider unhides) like there is on the primary display.

**Comment by jhasse** [comment]
The animation still doesn't work, right?
