### ISSUE TITLE
Date and Time on second(third, etc) panel

### ISSUE THREAD

**Issue by webstylr** [spin83/multi-monitors-add-on#36]
Hi and many thanks for this extension!

I guess this is a feature request: Would it be possible to have the date and time show up on any spawned panel?
For example, if you have a dual-monitor setup and run something in fullscreen on primary screen, having the date and time functionality on the second screen would be really really nice.

**Comment by ryanmt** [comment]
I mostly want the notifications dropdown from the date-time element on all monitors.

**Comment by renanbs** [comment]
I don't see that option "Show DateTime-Button on additional monitors." on my plugin preferences here.
I'm using Ubuntu 16.04 with gnome 3.18 from ~gnome3-team.

**Comment by ChrisCheney** [comment]
I have an open BZ about this issue, more or less, with gnome-shell and Florian thinks they would need to implement a proper top bar in gnome-shell itself to be able to allow extensions in general to be on whichever, or all, screens in a multi monitor setup. More users mentioning they would like this might help, so far it appears I may be the only one that has requested this via BZ in the 6+ years of gnome-shell.

https://bugzilla.gnome.org/show_bug.cgi?id=780078

**Comment by spin83** [comment]
Resolved by commit 77e01977bb366a33c55fd78fa8f0fadcd9d0a4ee
