### ISSUE TITLE
"Activities" not translated on second monitor

### ISSUE THREAD

**Issue by jhasse** [spin83/multi-monitors-add-on#38]
The text of the Activities button on my second monitor is in English and not translated to "Aktivitäten" (German) like the one on my primary monitor.

**Comment by spin83** [comment]
I can’t reproduce this bug.  What version of gnome-shell are you using?

**Comment by jhasse** [comment]
3.22

**Comment by spin83** [comment]
I tested on that version and it’s ok.
Could you specify some additional information?
Exact name of language form _Region & Language_ window (Gnome Settings).
Result of command _gnome-shell --version_
What distribution do you use?

**Comment by jhasse** [comment]
> Exact name of language form Region & Language window (Gnome Settings).
Deutsch (Deutschland)

`$LANG` is set to `de_DE.UTF-8`

> Result of command gnome-shell --version

3.22.2

> What distribution do you use?

Fedora 25

**Comment by spin83** [comment]
I can’t reproduce this issue. I tested on several devices with Fedora 25 and it display correctly.

**Comment by cra0zy** [comment]
Can you somehow read the text from the real activities button and use that instead of hardcoded "Activities" text? I say that because themes can change what the button says (take Arc theme for example).

**Comment by cra0zy** [comment]
Actually I stand corrected about the Arc theme, it is not using any text but instead it's using an image.

**Comment by spin83** [comment]
This issue is not caused by this extension and it is related to “User themes” extension. To fix this issue turn off “User themes” extension, restart gnome-shell and turn on back “User themes” extension.
