### ISSUE TITLE
Not working with gnome-shell 3.22.2+18+gdf7727a-1 on Arch

### ISSUE THREAD

**Issue by despian** [spin83/multi-monitors-add-on#41]
Since upgrading gnome-shell the plugin fails to load with error:

Settings schema 'org.gnome.shell.extensions.multi-monitors-add-on' does not contain a key named 'show-date-time'

**Comment by smcdougall** [comment]
Replied to you on AUR, but I thought I'd just add a quick note here as well.

Try removing both the AUR package and any copy installed from extensions.gnome.org (located in `~/.local/share/gnome-shell/extensions`), then reinstalling the AUR package.  Probably won't help, but it might be worth a shot.

My message on the AUR is longer, so check that. :smiley:

Also, @spin83 sometimes takes awhile to check GitHub, so hang in there and don't be discouraged if he doesn't reply for a bit.

**Comment by despian** [comment]
Thanks. I did try that and the issue seems to be the same.

Are you able to run the plugin on Arch with this version of gnome-shell?

**Comment by smcdougall** [comment]
So, I've gotten my Arch system up-to-date, and unfortunately I'm not seeing this issue.  I'm running `3.22.2-2`, the "current" version at the time of this comment.  There is an update, `3.22.3-1` about to be rolled out though, so you could check and see if that fixes the issue.

Have you tried using the version from [extensions.gnome.org](https://extensions.gnome.org/extension/921/multi-monitors-add-on/)?  The option to show the clock on your second monitor is new, and doesn't seem to be rolled out there yet.

The new option isn't entirely working for me either.  The clock text displays the wrong color on my second monitor when using the "[Arc](https://github.com/horst3180/Arc-theme)" shell theme (not when using other themes though).  Also, when I click on it, the notifications/calendar menu doesn't open.

You could try disabling the "Show DateTime-Button" option and see if you still get the crash.  Just trying to offer some workarounds until this gets figured out. :wink:

Hopefully this gets figured out soon. :confused:

**Comment by spin83** [comment]
Settings schema keys are recreated automatically when extension is loaded by gnome-shell. 
It’s look like some local problem witch configuration (dconf) or maybe schema file. 
Could you create new user account, login to gnome witch this new user and cheek if problem still exist.  

Notifications/calendar is not implemented.
