### ISSUE TITLE
With a panel on the second Monitor enabled, the menus move away from the menu bar

### ISSUE THREAD

**Issue by isantop** [spin83/multi-monitors-add-on#48]
When I have the Panel enabled on the second monitor, menus become detached from the menubar and move halfway down the window (happens in windows with regular menubars, like the terminal. Disabling the second monitor causes the menus to work again.

**Comment by spin83** [comment]
To work around that problem all displays must be aligned to top line.

**Comment by AnzoDK** [comment]
> To work around that problem all displays must be aligned to top line.

Yea - but my monitors are of different size - So that is not a solution

**Comment by zeparu** [comment]
with the current version the the extensions.gnome.org site on gnome 3.36, i no longer have this problem

**Comment by spin83** [comment]
Yes, it was fixed upstream in gnome-shell.
