### ISSUE TITLE
Gnome shell crash if additonal monitor pluged when Activities overview opened

### ISSUE THREAD

**Issue by n-goncharuk** [spin83/multi-monitors-add-on#49]
steps to reproduce (Fedora 25, Wayland, gnome-shell --version GNOME Shell 3.22.3. I have enabled only "Thumbnails-Slider on additional monitors" in extension settings)
1. unplug a secondary monitor
2. open activities overview
3. plug the monitor back
Session quits and you see a gdm login screen.

If extension disabled activities overview closing and you see your desktop, no crashes.

**Comment by spin83** [comment]
This issue has been fixed upstream in GNOME 3.24
