### ISSUE TITLE
AppMenu-Button doesn't show selected app on second monitor

### ISSUE THREAD

**Issue by krisgospc** [spin83/multi-monitors-add-on#51]
When the AppMenu-Button is on on the second monitor, it only shows what is selected on the first. I have recorded a Loom video of the issue here: https://www.useloom.com/share/0963ef6cf90a4e4292cac35f737b188e

**Comment by alex-kowalczyk** [comment]
Confirming the issue, have the same.

**Comment by sebastiaanfranken** [comment]
I also have this issue.

**Comment by rick-pri** [comment]
I have the foreground app on two out of three monitors, so I have the same/similar issue.

**Comment by spin83** [comment]
This is a duplicate of issue #46 .
