### ISSUE TITLE
Broken for Gnome Shell 3.24.2

### ISSUE THREAD

**Issue by ser** [spin83/multi-monitors-add-on#53]
It's broken for Gnome Shell 3.24.2 - instead of creating the second panel on the top of the second monitor, it creates second panel under first panel on the primary monitor.

**Comment by jtmkrueger** [comment]
@ser this seemed to work just fine for me. Perhaps you have some other extensions or tweaks that are getting in the way? Can you confirm that it's still non-functional with all other tweaks and extensions turned off?

**Comment by ser** [comment]
Hi, I've just downloaded your extension again and turned on without issues. It works now as it should. The same small set of other extensions I had before.
