### ISSUE TITLE
Please consider tagging releases

### ISSUE THREAD

**Issue by highvoltage** [spin83/multi-monitors-add-on#56]
Thanks for this great extension! Would you consider creating tags in git so that releases can be tracked? I'm the packager for this extension in Debian (that also makes its way into Ubuntu/Mint/etc) and it would make it easier to make sure we have the latest release package rather than manually checking the commit history. Thanks!

**Comment by spin83** [comment]
Yes. 
It will be synchronized with version from extensions.gnome.org

**Comment by highvoltage** [comment]
Great, thanks! I see version 13 is tagged, closing issue...
