### ISSUE TITLE
Activities button shifted

### ISSUE THREAD

**Issue by lcavalli** [spin83/multi-monitors-add-on#6]
Hi,
using this extension I'm having a little issue.
The activities button on primary display (I disabled the activities button on secondary display) after a while shifts a few pixels to the right.
See attached screenshot:
![screenshot from 2015-01-22 08 46 51](https://cloud.githubusercontent.com/assets/6123641/5852387/25567a3e-a216-11e4-8a00-385d537a0db3.png)

My other enabled extensions are:
`'MinimizedWindowsList@b3e.net',`
`'alternate-tab@gnome-shell-extensions.gcampax.github.com',`
`'jam-proxy-switcher@interhosting.us',`
`'world_clock@ailin.nemui',`
`'nohotcorner@azuri.free.fr',`
`'SmallPanelIcon@camporez.com',`
`'topIcons@adel.gadllah@gmail.com',`
`'gnome-shell-open-terminal@hackunix.org',`
`'multi-monitors-add-on@spin83'`

**Comment by spin83** [comment]
I can't reproduce this bug.
Extension 'SmallPanelIcon@camporez.com' is not compatible with this extension.
Which version of gnome-shell you are using?

**Comment by lcavalli** [comment]
GNOME Shell 3.14.3.
Cannot test right now disabling SmallPanelIcon extension. Will do next week and let you know.

Thanks,

Luca

**Comment by lcavalli** [comment]
Hi,

unluckily even with the 'SmallPanelIcon@camporez.com' extension disabled the issue is still present on my system.

Any other check I can do to help you?

**Comment by lcavalli** [comment]
I have to correct my previous comment. It seems that without 'SmallPanelIcon@camporez.com' extension Activities button keeps correctly aligned. Yeah!

**Comment by lcavalli** [comment]
Closing after few days of test without 'SmallPanelIcon@camporez.com' extension. It seems to work flawlessly.
