### ISSUE TITLE
Dialog opens at weird place

### ISSUE THREAD

**Issue by yfiua** [spin83/multi-monitors-add-on#61]
All gnome notifications (e.g., facebook) and system dialogs, including screenshot and the preference of this add-on, open at weird place if in ``Display'', monitors are arranged not exactly horizontally, and ``show panels on additional monitors'' is chosen at.

**Comment by spin83** [comment]
This issue is a duplicate of #48

**Comment by spin83** [comment]
Fixed upstream in gnome-shell.
