### ISSUE TITLE
Activities Overview Hot Corner OFF - ignored 

### ISSUE THREAD

**Issue by awenger** [spin83/multi-monitors-add-on#64]
I disabled the "Activities Overview Hot Corner" settings in the Tweaks tool (Top Bar section). With the extension disabled, the hot corners are not active. If I enable the multi monitors add-on extension the Hot Corners are active again.
The cursor often get stuck at the second screens Hot Corner if I move the cursor from the second to the main screen (right -> left)

**Comment by dberner** [comment]
+1

**Comment by jbicha** [comment]
For reference, Ubuntu 17.10 and 18.04 LTS includes the patch from https://gitlab.gnome.org/GNOME/gnome-shell/merge_requests/45

I am unaware of other distros using that patch so you can't assume that that particular schema exists but if it does exist, it would be nice to honor it.

**Comment by awenger** [comment]
Oh I didn't know this is a Ubuntu only thing, thanks for the info.
