### ISSUE TITLE
Thumbnail slider not working in Ubuntu 18.04 (Bionic Beaver), Gnome 3.28.1

### ISSUE THREAD

**Issue by pospeselr** [spin83/multi-monitors-add-on#65]
When multi-monitor thumbnail slider is enabled on all desktops, only the 'tray' appears on the non-main monitors and you cannot drag windows to them.  Thumbnail slider on the main monitor works as expected.  Screenshot is attached (with window contents blocked out).

![Activities Overview Screenshot](https://user-images.githubusercontent.com/2148104/39398912-bc5540fa-4ac9-11e8-859d-77ba4adaf349.png)

**Comment by mmohaveri** [comment]
I have the same problem.
If you have absolutely no window in the secondary monitor, everything works fine.
![](https://user-images.githubusercontent.com/6017468/39427359-b1c58afc-4c98-11e8-8acc-b4e7727d77d3.png)

If you move a window to the secondary monitor, at first it shows it twice. In the following image, there is only on 'google' window in the secondary monitor in the forth workspace (is was moved from first workspace of the primary monitor)

![newly moved 2](https://user-images.githubusercontent.com/6017468/39427606-a74d20e8-4c99-11e8-8a64-06f6ff9a18d0.png)

After moving, workspaces equal or lower to the one that it has a window on will not be shown.

![after moving 2](https://user-images.githubusercontent.com/6017468/39427655-d9aa9ed0-4c99-11e8-902b-1a1cf02e9333.png)

**Comment by spin83** [comment]
Could you try, if this issue still occur with latest code from master branch.

**Comment by mmohaveri** [comment]
@spin83 I pulled the master branch ([72bc548](https://github.com/spin83/multi-monitors-add-on/commit/72bc548b6533e08d6010bb6a9df09b9dc561bd82l)) and now it only shows one workspace from the secondary display.

**Comment by hswong3i** [comment]
![works](https://user-images.githubusercontent.com/780562/39915997-f5dedb48-553b-11e8-8879-f858edfccad1.png)

After reinstall from master (15d4e9c064a7f7fc5f8129fc9c967b1d2af1e40c), it now works with Ubuntu Bionic, diag-and-drop windows and other actions works perfectly, @spin83 thank you very much ;-)

**Comment by Naouak** [comment]
Also pulled latest master and it works correctly for me too. Thanks!

**Comment by fkopietz** [comment]
Great work! Thank you very much! :+1:

**Comment by tenwalls** [comment]
@spin83 Top work! TY

**Comment by pospeselr** [comment]
Confirmed! Cloned master and installed and now everything is working again!

**Comment by fvmarees** [comment]
Been using this extension for years and am loving. Can also confirm pulling from master and reinstalling fixes the abovementioned problems after upgrading a Gnome Ubuntu LTS 16.04.5 -> Ubuntu LTS 18.04.1 .. awesome work, thanks! :)
