### ISSUE TITLE
show thumbnail slider on additional monitors not working

### ISSUE THREAD

**Issue by mossad-zika** [spin83/multi-monitors-add-on#67]
Thx for awesome extension

Unfortunately, thumbnail not working on additional monitor

Ubuntu 18.04

**Comment by wojnicki** [comment]
The slider seems to be working fine as long as I place no windows on the secondary monitor. As soon as I place a window there (using at least 2nd workspace), it starts acting funny. Here are are screenshot. First two are ok, the third shows the problem.
![screenshot from 2018-06-08 22-02-04](https://user-images.githubusercontent.com/15322325/41178594-0e15298c-6b68-11e8-9c0d-1e95b62ee4a6.png)
![screenshot from 2018-06-08 22-02-11](https://user-images.githubusercontent.com/15322325/41178595-0e3152d8-6b68-11e8-952f-bff42b90bf8e.png)
![screenshot from 2018-06-08 22-02-32](https://user-images.githubusercontent.com/15322325/41178596-0e4dc846-6b68-11e8-8f9b-79d1dd2040b5.png)

**Comment by spin83** [comment]
It’s look like copy of issue #65. Please try to use latest version.

**Comment by wojnicki** [comment]
Thanks, works fine now :)
