### ISSUE TITLE
Individual positioning of Thumbnails-Slider for 3 (and more) monitors configuration

### ISSUE THREAD

**Issue by sliwowitz** [spin83/multi-monitors-add-on#69]
Would it be possible to configure the position (left/right) of the Thumbnails-Slider fore each additional monitor separately? 

I'm on a 3 monitor setup and I would like to have the slider at the left side of the right monitor, and at the right side of the left one so that the overviews are all close to the central monitor, and I wouldn't have to turn my head to see the far one.

---
And thank you for this extension. It really helps me get my workspaces organized.

**Comment by spin83** [comment]
Functionality added by the user @axxapy
