### ISSUE TITLE
gnome-shell 3.30.2 breaks thumbnails-slider

### ISSUE THREAD

**Issue by ewaves** [spin83/multi-monitors-add-on#76]
Downgrading gnome-shell to 3.30.1 fixes the issue and the additional thumbnail-slider reappears. Tested on Arch linux and fedora 29.

**Comment by phaleintx** [comment]
Observing an error with latest multi-monitor-plugin v16 on Fedora 29 after recent upgrade of gnome-shell to 3.30.2.  Getting a generic "Error" and the plugin won't load.

**Comment by ewaves** [comment]
The faulty commit may be this one https://gitlab.gnome.org/GNOME/gnome-shell/commit/f1195ecb013e930899866a5cbc5f20dccf5417f8

**Comment by HankB** [comment]
Add me as a "me too." This is on Debian Buster and with 
```text
hbarta@rocinante:~$ dpkg -l gnome-shell
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=====================================
ii  gnome-shell    3.30.1-2     amd64        graphical shell for the GNOME desktop
hbarta@rocinante:~$ 
```
I don't know how to determine the Multi-Monitor version but it is up to date as of 2019-02-26 according to https://extensions.gnome.org/local/
