### ISSUE TITLE
Enables active corners

### ISSUE THREAD

**Issue by ilyachch** [spin83/multi-monitors-add-on#87]
Ubuntu 18.04, Gnome-shell version: 3.28.3

After installing this extension, active corners becomes enabled (in gnome-tweak-tool it's off).

If I turn it on and off, it becomes normal, but after a reboot or gnome-shell restart it activates again

**Comment by ruedigerkupper** [comment]
Confirmed and annpying: Even when I turn off the "activities" menu on the external monitor, the active corner stays there. It is very easy hitting it accidentally when moving the mouse from one monitor to the other. It always disrupts my work flow.
Please make the add on not activate the active corners if they are disabled in tweak tool. And disable the active corner, when the activities menu is not shown. Thanks!

**Comment by andersgb1** [comment]
Same here.
