### ISSUE TITLE
Error loading extension on ubuntu 18.04

### ISSUE THREAD

**Issue by lpanebr** [spin83/multi-monitors-add-on#89]
After installing, enabling and restarting I get this error on the exclamation mark:
 - "Error loading extension"

Any idea ass how to get it to work?
What info should I send to help?
I'm running ubuntu 18.04 that was upgraded from 16.04.

![image](https://user-images.githubusercontent.com/129185/56893517-50199c00-6a59-11e9-99d5-e15d403f775f.png)

**Comment by noothangpersonel** [comment]
I had to install libxml2-utils:
`sudo apt install libxml2-utils`

**Comment by rubensa** [comment]
On my **Ubuntu 18.04** fails too (I have package libxml2-utils installed).  I can see this on **journalctl** output:

gnome-shell[3715]: Extension "multi-monitors-add-on@spin83" had error: **TypeError: propertyNames.values is not a function**
gnome-software[4139]: no app for changed multi-monitors-add-on@spin83

That is used on **extension.js** (line 48).  Looks like there is some kind of JS imcompatibility in the copyClass function.

**Comment by rubensa** [comment]
I could fix that by changing extension.js copyClass function from:

```javascript
function copyClass (s, d) {
//	global.log(s.name +" > "+ d.name);
	let propertyNames = Object.getOwnPropertyNames(s.prototype);
	for (let pName of propertyNames.values()) {
//		global.log(" ) "+pName);
		if (d.prototype.hasOwnProperty(pName)) continue;
	  	if (pName === "prototype") continue;
	  	if (pName === "constructor") continue;
//	  	global.log(pName);
        let pDesc = Object.getOwnPropertyDescriptor(s.prototype, pName);
        Object.defineProperty(d.prototype, pName, pDesc);
	}
};
```

to:

```javascript
function copyClass (s, d) {
//	global.log(s.name +" > "+ d.name);
	let propertyNames = Object.keys(s.prototype);
	for (let pName of propertyNames) {
//		global.log(" ) "+pName);
		if (d.prototype.hasOwnProperty(pName)) continue;
	  	if (pName === "prototype") continue;
	  	if (pName === "constructor") continue;
//	  	global.log(pName);
        let pDesc = Object.getOwnPropertyDescriptor(s.prototype, pName);
        Object.defineProperty(d.prototype, pName, pDesc);
	}
};
```

but now I have this error message:

gnome-shell[3715]: Extension "multi-monitors-add-on@spin83" had error: **TypeError: GObject.registerClass() used with invalid base class (is PanelMenuButton)**
gnome-software[4139]: no app for changed multi-monitors-add-on@spin83

Looks like I have to upgrade to **Gnome Shell 3.32** (not available on Ubuntu 18.04 by now) or download [v16](https://github.com/spin83/multi-monitors-add-on/releases/tag/v16) (that should be compatible with GNOME Shell 3.28)

**Comment by rubensa** [comment]
Looks like [v16](https://github.com/spin83/multi-monitors-add-on/releases/tag/v16) is working fine.

**Comment by lpanebr** [comment]
I got it to work some time ago but forgot to update this issue and now unfortunately I can't remember what was that fixed it.. sorry
