### ISSUE TITLE
typeError: propertyNames.values is not a function

### ISSUE THREAD

**Issue by nikosgevre** [spin83/multi-monitors-add-on#99]
Title says it all. How can I fix this error? I am using gnome version 3.28.4 and ubuntu 18.04

**Comment by spin83** [comment]
I can't reproduce this error, what version of extension are you using?

**Comment by nikosgevre** [comment]
Not sure. How can I check that? I guess the latest since I downloaded the extension in the last week

**Comment by spin83** [comment]
There was an invalid link, please try download extension from this branch [gnome-3-24_3-30](https://github.com/spin83/multi-monitors-add-on/tree/gnome-3-24_3-30)

**Comment by nikosgevre** [comment]
fixed
